In [ ]:
from google.colab import drive
import sys
drive.mount('/content/drive')
sys.path.append('/content/drive/MyDrive/exam_B/spotify-2023.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/exam_B/spotify-2023.csv', encoding='latin1')
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

A. Cargue los datos e identifique cuantas variables categóricas (tipo object) y cuantas variables numéricas tiene.

In [ ]:
df = df.info() #El Dataframe tiene 7 variables categoricas y 17 variables númericas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
dtypes: int64(17), object(7)
memory usage: 178.8+ KB

B.Desarrolle un algoritmo que nos diga cuantas canciones de Coldplay hay en la base de datos.

In [ ]:
df['artist(s)_name'].unique()

array(['Latto, Jung Kook', 'Myke Towers', 'Olivia Rodrigo',
       'Taylor Swift', 'Bad Bunny', 'Dave, Central Cee',
       'Eslabon Armado, Peso Pluma', 'Quevedo', 'Gunna',
       'Peso Pluma, Yng Lvcas', 'Bad Bunny, Grupo Frontera', 'NewJeans',
       'Miley Cyrus', 'David Kushner', 'Harry Styles', 'SZA',
       'Fifty Fifty', 'Billie Eilish', 'Feid, Young Miko', 'Jimin',
       'Gabito Ballesteros, Junior H, Peso Pluma', 'Arctic Monkeys',
       'Bizarrap, Peso Pluma', 'The Weeknd, Madonna, Playboi Carti',
       'Fuerza Regida', 'Rï¿½ï¿½ma, Selena G', 'Tainy, Bad Bunny',
       'Morgan Wallen', 'Dua Lipa', 'Troye Sivan',
       'Peso Pluma, Grupo Frontera',
       'The Weeknd, 21 Savage, Metro Boomin', 'Karol G, Shakira',
       'Big One, Duki, Lit Killah, Maria Becerra, FMK, Rusherking, Emilia, Tiago pzk',
       'Yahritza Y Su Esencia, Grupo Frontera', 'Junior H, Peso Pluma',
       'Post Malone, Swae Lee', 'Bebe Rexha, David Guetta',
       'Tyler, The Creator, Kali Uchis', 'Nicki Minaj, Aqua, Ice Spice',
       'OneRepublic', 'The Weeknd', 'The Weeknd, Daft Punk',
       'Ariana Grande, The Weeknd', 'Feid, Myke Towers, Sky Rompiendo',
       'David Guetta, Anne-Marie, Coi Leray', 'Karol G', 'Peggy Gou',
       'Tom Odell', 'Kali Uchis', 'Manuel Turizo',
       'dennis, MC Kevin o Chris', 'PinkPantheress, Ice Spice',
       'Charlie Puth, BTS, Jung Kook', 'Rauw Alejandro, ROSALï¿½',
       'Ozuna, Feid', 'Chris Molitor', 'Libianca', 'Post Malone',
       'Rauw Alejandro, Bizarrap', 'Glass Animals', 'JVKE',
       'The Neighbourhood', 'Bizarrap, Quevedo', 'Coldplay', 'd4vd',
       'Sam Smith, Kim Petras', 'Yandel, Feid', 'Maria Becerra',
       'Vance Joy', 'Em Beihold, Stephen Sanchez',
       'Mc Livinho, DJ Matt D', 'Justin Bieber, The Kid Laroi',
       'Marshmello, Manuel Turizo', 'Lewis Capaldi',
       'Chencho Corleone, Bad Bunny', 'Jain', 'Ayparia, unxbected',
       'Luke Combs', 'Doechii', 'Bad Bunny, Eladio Carrion', 'Jung Kook',
       'J. Cole, Lil Durk', 'Lana Del Rey', 'BTS',
       'Future, Metro Boomin, Don Toliver', 'Eminem', 'Carin Leon',
       'Dua Lipa, Elton John, Pnau', 'Ruth B.', 'Imagine Dragons',
       'Adele', 'Kendrick Lamar, Jay Rock', 'Anggi Marito',
       'Jasiel Nuï¿½ï¿½ez, Peso P', 'Tears For Fears', 'J. Cole',
       'Loreen', 'Taiu, Milo j', 'Sebastian Yatra, Manuel Turizo, Beï¿½ï',
       'Calvin Harris, Ellie Goulding', 'Sabrina Carpenter',
       'Carin Leon, Grupo Frontera', 'Peso Pluma', 'Feid',
       'Ray Dalton, Ryan Lewis, Macklemore', 'Billie Eilish, Khalid',
       '(G)I-DLE', 'Shakira, Bizarrap',
       'Swae Lee, A Boogie Wit da Hoodie, Metro Boomin, NAV',
       'Travis Scott, Young Thug, Metro Boomin',
       'Sachin-Jigar, Shadab Faridi, Altamash Faridi, Amitabh Bhattacharya, Varun Jain',
       'Ed Sheeran', 'Veigh, Bvga Beatz, Supernova Ent, Prod Malax',
       'Mc Pedrinho, DJ 900', 'Sog, Ryan Castro, Peso Pluma',
       'The Weeknd, Lana Del Rey', 'Bomba Estï¿½ï¿½reo, Bad B', 'Keane',
       'New West', 'Chino Pacas', 'Natanael Cano', 'Don Omar, Lucenzo',
       'Ana Castela, AgroPlay', 'Bruno Mars',
       'Big One, FMK, Ke personajes', 'Drake, 21 Savage', 'Justin Bieber',
       'Chris Brown', 'Natanael Cano, Peso Pluma', 'Daddy Yankee',
       'Drake, WizKid, Kyla', 'Miguel', 'The Police', 'Lord Huron',
       'Rihanna, Calvin Harris', 'Alec Benjamin',
       'A$AP Rocky, Metro Boomin, Roisee', 'YOASOBI', 'Rosa Linn',
       'One Direction', 'Oscar Maydon, Junior H', 'Radiohead',
       'James Arthur', 'Cigarettes After Sex', 'Shubh', 'Frank Ocean',
       'Hozier', 'Fuerza Regida, Grupo Frontera', 'Hotel Ugly',
       'Creedence Clearwater Revival', 'Plan B',
       'Feid, Mora, Saiko, Quevedo', 'a-ha',
       'Swae Lee, Lil Wayne, Offset, Metro Boomin',
       'Kodak Black, NLE Choppa, Muni Long, JVKE, Jimin', 'Shakira',
       'Natanael Cano, Gabito Ballesteros, Peso Pluma',
       'Arijit Singh, Sachin-Jigar, Amitabha Bhattacharya', 'Stray Kids',
       'Becky G, Peso Pluma', 'Metro Boomin, Coi Leray', 'Kaliii, Kaliii',
       'Junior H, Eden Muï¿½ï', 'Abhijay Sharma, Riar Saab',
       'Semicenk, Doï¿½ï¿½u ', 'JISOO',
       'Future, Lil Uzi Vert, Metro Boomin', 'RAYE, 070 Shake',
       'Arcangel, Bad Bunny', 'Taylor Swift, Ice Spice',
       'Future, Chris Brown, Metro Boomin', 'BLESSD, Peso Pluma',
       'Fuerza Regida, Natanael Cano', 'Lana Del Rey, Taylor Swift',
       'Coi Leray', 'ENHYPEN', 'Lil Durk, Morgan Wallen',
       'James Blake, Metro Boomin', 'Israel & Rodolffo, Mari Fernandez',
       'Steve Lacy', 'Beyoncï¿', 'Halsey, Suga', 'Nicky Jam, Feid',
       'Sean Paul, Feid', 'Drake', 'Kendrick Lamar, Beyoncï¿',
       'WizKid, Toian, Metro Boomin, Don Toliver, Beam', 'Simone Mendes',
       'Tini', 'Lil Uzi Vert', 'Sia', 'Stephen Sanchez',
       'MC Caverinha, KayBlack', 'Offset, JID', 'Zï¿½ï¿½ Neto & Crist',
       'Migrantes, LiL CaKe, Nico Valdi', 'Tory Lanez', 'Joji',
       'Mambo Kingz, DJ Luian, Anuel Aa', 'Nile Rodgers, LE SSERAFIM',
       'Agust D', 'Rich The Kid, Matuï¿', 'Labrinth',
       'Karol G, Romeo Santos', 'Lizzy McAlpine', 'IVE', 'sped up 8282',
       'Cartel De Santa, La Kelly', 'SEVENTEEN', 'NLE Choppa',
       'The Weeknd, Future', 'Nicki Minaj, Ice Spice',
       'Grupo Marca Registrada, Grupo Frontera',
       'Fuerza Regida, Peso Pluma', 'TAEYANG, Lisa', 'Raim Laode',
       'ROSALï¿½', 'Meghan Trainor',
       'sped up nightcore, ARIZONATEARS, Lil Uzi Vert', 'Grupo Frontera',
       'TV Girl', 'INTERWORLD', 'Quevedo, Jhayco',
       'El Chachito, Junior H', 'The Weeknd, Gesaffelstein', 'RM, Colde',
       'BLACKPINK', 'Nengo Flow, Bad Bunny', 'Nicky Youre, Dazy',
       'Eminem, Dina Rae', 'IU, Agust D', 'Arcangel, Bizarrap',
       'Tyler, The Creator', 'Tiï¿½ï¿½sto, Tate M', 'NF', 'Yng Lvcas',
       'Kanii, PR1ISVX', 'Marï¿½ï¿½lia Mendo', 'Zach Bryan',
       'Melanie Martinez', 'Fuerza Regida, Chino Pacas', 'Mae Stephens',
       'Feid, Mora', 'Kenia OS', 'Kordhell', 'Coolio, L.V.',
       'Karol G, Ovy On The Drums', 'The Walters', 'Mac DeMarco',
       'Jack Black',
       'Duki, NICKI NICOLE, Cris Mj, Standly, Stars Music Chile',
       'Brray, Rauw Alejandro, Lyanno', 'Linkin Park',
       'Gorillaz, Bad Bunny', 'j-hope, J. Cole',
       'Robin Schulz, Oliver Tree', 'Don Toliver, Future, Justin Bieber',
       'Niall Horan', 'Central Cee', 'Mahalini',
       'Arijit Singh, Sachin-Jigar', 'ThxSoMch', 'Myke Towers, Quevedo',
       'Morgan Wallen, Eric Church', 'Nicki Minaj', 'Kaifi Khalil',
       'Karol G, Quevedo', 'Lady Gaga', 'Ozuna, Shakira', 'Leo Santana',
       'Treyce', 'Post Malone, Doja Cat',
       'MC Xenon, Os Gemeos da Putaria',
       'Imagine Dragons, League of Legends, JID, Arcane', 'XXXTENTACION',
       'Israel & Rodolffo, Ana Castela', 'J Balvin, Bad Bunny',
       'Yuridia, Angela Aguilar', 'The Kid Laroi', 'Lizzo', 'Fujii Kaze',
       'Wisin & Yandel, ROSALï¿½', 'King', 'Coldplay, BTS',
       'Sam Smith, Calvin Harris, Jessie Reyez', 'P!nk', 'LE SSERAFIM',
       'PinkPantheress', 'TAEYANG, Jimin', 'Rihanna', 'Lil Nas X',
       'Beach Weather', 'Halsey, BTS', 'Baby Tate', 'Rï¿½ï',
       'Arijit Singh, Vishal Dadlani, Sukriti Kakar, Vishal-Shekhar, Shekhar Ravjiani, Kumaar',
       'Beach House', 'BTS, Jung Kook, FIFA Sound',
       'Shakira, Rauw Alejandro', 'Steve Aoki, Tini, La Joaqui',
       'Sam Smith', 'Conan Gray',
       'Vishal-Shekhar, Shilpa Rao, Caralisa Monteiro, Kumaar, Vishal Dadlani, Shekhar Ravjiani',
       'Calvin Harris, Dua Lipa', 'TOMORROW X TOGETHER',
       'Drake, Future, Tems', 'Mr.Kitty', 'Gustavo Mioto, Mari Fernandez',
       'Jack Harlow, Lil Nas X', 'Elley Duhï¿', 'Seafret',
       'Baby Rasta, Rauw Alejandro',
       'DJ Escobar, MC MENOR SG, MC MENOR HR', 'Dean Lewis', 'Bellakath',
       'Skrillex, Flowdan, Fred again..',
       'Travis Scott, 21 Savage, Metro Boomin', 'Kate Bush', 'Aerosmith',
       'Freddie Dredd', 'Lost Frequencies, Calum Scott',
       'Twisted, Oliver Tree', 'Kenshi Yonezu', 'Omar Apollo',
       'Dua Lipa, DaBaby', 'Doja Cat', 'James Hype, Miggy Dela Rosa',
       'Pritam, Arijit Singh, Amitabh Bhattacharya',
       'Styrx, utku INC, Thezth', 'Maroon 5, Wiz Khalifa', 'Mariah Carey',
       'Wham!', 'Brenda Lee', 'Bobby Helms', 'Michael Bublï¿',
       'Ariana Grande', 'Andy Williams', 'Dean Martin', 'Kelly Clarkson',
       'Josï¿½ï¿½ Felic', 'The Ronettes',
       'John Lennon, The Harlem Community Choir, The Plastic Ono Band, Yoko Ono',
       'SZA, Don Toliver', 'Burl Ives', 'Nat King Cole', 'Paul McCartney',
       'Band Aid', 'SZA, Phoebe Bridgers', "Shakin' Stevens",
       'Frank Sinatra, B. Swanson Quartet', 'SZA, Travis Scott',
       'Bing Crosby, John Scott Trotter & His Orchestra, Ken Darby Singers',
       'Chris Rea', 'Darlene Love', 'Ed Sheeran, Elton John',
       'Perry Como, The Fontane Sisters, Mitchell Ayres & His Orchestra',
       'Britney Spears', 'Mabel Matiz, Mert Demir', 'RM',
       'Travis Scott, Metro Boomin', 'Taylor Swift, Lana Del Rey',
       'Dj LK da Escï¿½ï¿½cia, Tchakabum, mc jhenny, M',
       'Bad Bunny, Jhay Cortez', 'Gwen Stefani, Blake Shelton',
       'Chencho Corleone, Rauw Alejandro', 'Bad Bunny, Rauw Alejandro',
       'Chuck Berry', 'Frank Sinatra', 'John Legend, Metro Boomin',
       'Maldy, Karol G', 'Gayle',
       'Lauren Spencer Smith, Lauren Spencer Smith, Lauren Spencer Smith',
       'Cherish, ACRAZE',
       'Adassa, Mauro Castillo, Stephanie Beatriz, Encanto - Cast, Rhenzy Feliz, Diane Guerrero, Carolina Gaitan',
       'Farruko', 'Jaymes Young', 'The Weeknd, Tyler, The Creator',
       'SZA, Doja Cat', 'The Weeknd, Lil Wayne', 'Ckay', 'Jessica Darrow',
       'The Weeknd, Post Malone', 'Mï¿½ï¿½ne', 'Aitana, zzoilo',
       'Julieta Venegas, Bad Bunny, Tainy', 'Lisa', 'Tiï¿½ï¿½sto, Ava',
       'The Weeknd, Swedish House Mafia',
       'Juan Cruz Toledo, Huilen Toledo', 'BoyWithUke',
       'Xamï¿½ï¿½, Gustah, Neo B',
       'Lit Killah, Maria Becerra, Tiago pzk, NICKI NICOLE', 'Emmy Meli',
       'Justin Quiles, Lenny Tavï¿½ï¿½rez, BL', 'Shawn Mendes',
       'Kodak Black', 'Aventura, Bad Bunny', 'Rauw Alejandro',
       "Ckay, AX'EL, Dj Yo!", 'Bruno Mars, Anderson .Paak, Silk Sonic',
       'THE ANXIETY, Willow, Tyler Cole', 'Sebastian Yatra',
       'Justin Bieber, Daniel Caesar, Giveon', 'Bizarrap, Tiago pzk',
       'Stromae', 'Chris Brown, Rvssian, Rauw Alejandro',
       'NEIKED, Mae Muller, Polo G', 'Oliver Tree',
       'Kali Uchis, Amaarae, Moliy', 'Young Thug, Future, Gunna',
       'Doja Cat, The Weeknd', 'Jnr Choi', 'Trueno, Tiago pzk',
       'Sech, Bad Bunny, Mora', 'Drake, Project Pat, 21 Savage',
       'Tiï¿½ï¿½sto, Kar', 'Edison Lighthouse', 'The Weeknd, ROSALï¿½',
       'Olga Merediz, Stephanie Beatriz, Encanto - Cast', 'Surf Curse',
       'Jason Derulo', '21 Savage, Gunna', '24kgoldn, Iann Dior',
       'Stephanie Beatriz, Diane Guerrero', 'Trueno', 'Kanye West',
       'Playboi Carti', 'Maluma', 'Ed Sheeran, Fireboy DML',
       'Prezioso, Gabry Ponte, LUM!X', 'Tiï¿½ï¿',
       'Marï¿½ï¿½lia Mendonï¿½ï¿½a, George Henrique &', 'TWICE', 'Giveon',
       'Sean Paul, Dua Lipa',
       'Charli XCX, Jax Jones, Joel Corry, Saweetie', 'SALES',
       'Sleepy hallow', 'Masked Wolf', 'Anuel Aa, Jhay Cortez', 'NIKI',
       'Tate McRae', 'Avicii', 'Drake, Future, Young Thug',
       'Imagine Dragons, League of Legends, Arcane', 'Tones and I',
       'Juice WRLD', 'J Balvin, Maria Becerra', 'John Legend', 'Nirvana',
       'Duncan Laurence', 'Drake, Travis Scott', 'Tini, L-Gante', 'SiM',
       'Kendrick Lamar, Baby Keem', 'The Killers',
       'J Balvin, Nio Garcia, Bad Bunny', 'Lady Gaga, Bradley Cooper',
       'Marshmello, Jonas Brothers',
       'Riton, Nightcrawlers, Mufasa & Hypeman, Dopamine', 'Polo G',
       'Eminem, Nate Dogg', 'Maroon 5',
       'Arcangel, De La Ghetto, Justin Quiles, Lenny Tavï¿½ï¿½rez, Sech, Dalex, Dimelo Flow, Rich Music',
       'Gunna, Lil Baby', 'Katy Perry, Alesso',
       'Marï¿½ï¿½lia Mendonï¿½ï¿½a, Maiara &', 'Tini, Maria Becerra',
       'Anuel Aa, Myke Towers, Jhay Cortez', 'Karol G, Becky G',
       'Dr. Dre, Snoop Dogg', 'Dove Cameron', 'Ed Sheeran, Taylor Swift',
       'Charlie Puth', 'Kanye West, Alicia Keys, Fivio Foreign',
       'Mahmood, Blanco', '50 Cent', 'Yung Lean', 'Labrinth, Zendaya',
       'The Rare Occasions', 'Intense, AP Dhillon, Gurinder Gill',
       'Quevedo, La Pantera, Juseph, Cruz Cafunï¿½ï¿½, Bï¿½ï¿½jo, Abhir Hathi',
       'Dr. Dre, 2Pac, Roger', 'Eminem, Dr. Dre', 'Luude, Colin Hay',
       'Ryan Castro', 'Kendrick Lamar', 'Eminem, Dido',
       'GODZZ__-, Zakaria', 'Chase Atlantic', 'Em Beihold',
       'Mainstreet, Chefin', 'Alvaro Diaz, Rauw Alejandro',
       'Nicki Minaj, Lil Baby', 'Future', 'Zï¿½ï¿½ Fe', 'Muni Long',
       'Vundabar', 'V', 'Marï¿½ï¿½lia Mendonï¿½ï¿½a, Hugo & G',
       'Shawn Mendes, Camila Cabello', 'Daddy Yankee, Bad Bunny',
       'Dua Lipa, Megan Thee Stallion', 'Camila Cabello, Ed Sheeran',
       'Cris Mj', 'Anitta', 'Dave', 'Tulus', 'Mc Pedrinho, Pedro Sampaio',
       'Zion & Lennox', 'Residente, Bizarrap', 'Jack Harlow',
       'Eden Muï¿½ï', 'Treasure', 'Christian Nodal',
       'Kevin Gates, Juicy J', 'Tyga, Doja Cat', 'Queen', 'YEAT',
       'C. Tangana', 'The Chainsmokers, Coldplay',
       'The Chainsmokers, Halsey', 'NMIXX', 'Gotye, Kimbra',
       'AnnenMayKantereit, Giant Rooks', 'Paulo Londra', 'Danny Ocean',
       'Lil Tjay', 'Willow', 'Feid, Alejo, Robi', 'Demi Lovato',
       'Camila Cabello, Willow', 'Matuï¿½ï¿½, Wiu, ',
       'De La Ghetto, Duki, Quevedo', 'Lil Baby',
       'Ak4:20, Cris Mj, Pailita', 'Yahritza Y Su Esencia',
       'Luï¿½ï¿½sa Sonza, MC Frog, Dj Gabriel do Borel, Davi K',
       'Ed Sheeran, J Balvin', 'teto', 'Blackbear, BoyWithUke',
       'Pharrell Williams, Nile Rodgers, Daft Punk',
       "Jordan Fisher, Josh Levi, Finneas O'Connell, 4*TOWN (From Disney and Pixarï¿½ï¿½ï¿½s Turning Red), Topher Ngo, Grayson Vill",
       'BIGBANG', 'Kendrick Lamar, Blxst, Amanda Reifer',
       'Kendrick Lamar, Sampha', 'Post Malone, Roddy Ricch',
       'Kendrick Lamar, Kodak Black', 'Tony Dize, Bad Bunny',
       'Buscabulla, Bad Bunny', 'Kendrick Lamar, Taylour Paige',
       'Kendrick Lamar, Sam Dew, Baby Keem', 'Bad Bunny, The Marï¿½ï',
       'Kendrick Lamar, Ghostface Killah, Summer Walker',
       'Polima WestCoast, Pailita', 'Bad Bunny, Tainy',
       'Panic! At The Disco', 'Kendrick Lamar, Tanna Leone', 'PSY, Suga',
       'Benson Boone', 'KALUSH', 'Luciano', 'Bizarrap, Paulo Londra',
       'Shae Gill, Ali Sethi', 'Kendrick Lamar, Beth Gibbons',
       'Sech, Mora', 'MNEK, Jax Jones', 'Ugly Dray, Tesla Jnr',
       'Justin Bieber, Don Toliver', 'Jessi', 'Chanel', 'Leah Kate',
       'Sam Ryder', 'HA SUNG WOON, Jimin', 'The Goo Goo Dolls',
       'Kevin Kaarl', 'Suki Waterhouse', 'Lauren Spencer Smith',
       'Pharrell Williams, Tyler, The Creator, 21 Savage',
       'Calvin Harris, Dua Lipa, Young Thug',
       'Nengo Flow, Anuel Aa, Chris Jedi, Chencho Corleone',
       'Kanye West, XXXTENTACION', 'Musical Youth',
       'Bizarrap, Villano Antillano', 'Halsey', 'BYOR, Imanbek',
       'Sleepy hallow, 347aidan', 'Paloma Faith', 'Marshmello, Khalid',
       'Ozuna, Tiago pzk', 'Childish Gambino',
       'David Guetta, Ella Henderson, Becky Hill', 'Duki',
       'Sidhu Moose Wala', 'Keisya Levronka', 'Victor Cibrian',
       'Metallica',
       'De La Ghetto, Feid, Polima WestCoast, Paloma Mami, Pailita',
       'Yung Gravy', 'Lasso', 'Nayeon', 'Schï¿½ï¿½rze, DJ R', 'j-hope',
       "Guns N' Roses", 'Burna Boy', 'Kanye West, Lil Durk, Cardi B',
       'L7nnon, DJ Biel do Furduncinho, Bianca', 'Anitta, Tini, Becky G',
       'Nessa Barrett', 'LF System',
       'Mc Vitin Da Igrejinha, MC Tairon, DJ Win', 'Rels B',
       'Snoop Dogg, BTS, Benny Blanco', 'Drake, DJ Khaled, Lil Baby',
       'Luar La L', 'Ghost', 'Rex Orange County', 'Sofia Carson',
       'Grupo Marca Registrada, Junior H',
       'Calvin Harris, Halsey, Pharrell Williams, Justin Timberlake',
       'Peso Pluma, Luis R Conriquez', 'Luis R Conriquez, La Adictiva',
       'David Guetta, Shakira, Black Eyed Peas',
       'Melody, Ana Castela, Dj Chris No Beat',
       'Elton John, Britney Spears',
       'Interplanetary Criminal, Eliza Rose', 'Armani White', 'Oxlade',
       'PnB Rock', 'Ovy On The Drums, Quevedo', 'Lil Yachty',
       'Marshmello, Juice WRLD',
       'Fran C, Polima WestCoast, Nickoog Clk, Pablito Pesadilla',
       'Southstar', 'girl in red', 'Rosa Walton, Hallie Coggins',
       'Luciano, Aitch, Bï¿½', 'MC Ryan SP, Love Funk, Mc Paiva ZS',
       'Drake, Travis Scott, 21 Savage', 'Ludwig Goransson, Foudeqush',
       'Jin', 'Selena Gomez', 'Feid, Paulo Londra', 'Feid, Sech, Jhayco'],
      dtype=object)

In [ ]:
registro=0
for Coldplay in df['artist(s)_name'].unique():
     if Coldplay == df['track_name']:
       registro=registro+1
print("el numero de canciones es:",registro)

TypeError: 'NoneType' object is not subscriptable

C. Encuentre el máximo y el mínimo de cada columna numérica en la base de datos.

In [ ]:
df.describe().iloc[[3,7]]

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
min,1.0,1930.0,1.0,1.0,31.0,0.0,0.0,0.0,0.0,65.0,23.0,4.0,9.0,0.0,0.0,3.0,2.0
max,8.0,2023.0,12.0,31.0,52898.0,147.0,672.0,275.0,58.0,206.0,96.0,97.0,97.0,97.0,91.0,97.0,64.0

D. Desarrolle una función que reciba como parámetro su base de datos y un artista y le devuelva todas las canciones de ese artista en base de datos.

In [ ]:
def c_artista(df,artista):
  A=df[df["artist(s)_name"]==artista]
  Temas_artista=A[["artist(s)_name","track_name"]]
  return Temas_artista
nombre_artista=input("ingrese el cantante: ")
print(c_artista(df,nombre_artista))

ingrese el cantante: Feid
    artist(s)_name                    track_name
125           Feid      Feliz Cumpleaï¿½ï¿½os Fe
221           Feid        CHORRITO PA LAS ANIMAS
227           Feid                        Normal
300           Feid               REMIX EXCLUSIVO
885           Feid  Si Te La Encuentras Por Ahï¿
906           Feid                    Ferxxo 100
908           Feid                    Prohibidox
916           Feid                  Lady Mi Amor

E. Cree una tabla con una función de agregación, que muestre la sumatoria de cuantas canciones Taylor Swift y Coldplay aparecen en playlist.

In [ ]:
table = pd.pivot_table(data=df, index='artist(s)_name', values='track_name', aggfunc="count")
table = table[table.index.isin(['Taylor Swift', 'Coldplay'])]
table

                track_name
artist(s)_name
Coldplay                 3
Taylor Swift            34